"""add outbox table

Revision ID: c4292361a706
Revises: 
Create Date: 2026-01-28 15:38:28.391652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'c4292361a706'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idempotency_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=128), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=False),
    sa.Column('response_body', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scope', 'key', name='uq_idem_scope_key')
    )
    op.create_index(op.f('ix_idempotency_records_key'), 'idempotency_records', ['key'], unique=False)
    op.create_index(op.f('ix_idempotency_records_scope'), 'idempotency_records', ['scope'], unique=False)
    op.create_table('outbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('topic', sa.String(length=64), nullable=False),
    sa.Column('destination', sa.String(length=256), nullable=False),
    sa.Column('payload', sqlite.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.String(length=512), nullable=True),
    sa.Column('send_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outbox_topic'), 'outbox', ['topic'], unique=False)
    op.create_table('pawapay_deposits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('deposit_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('business_id', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.String(length=256), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('deposit_id', name='uq_pawapay_deposit_id')
    )
    op.create_index(op.f('ix_pawapay_deposits_business_id'), 'pawapay_deposits', ['business_id'], unique=False)
    op.create_index(op.f('ix_pawapay_deposits_deposit_id'), 'pawapay_deposits', ['deposit_id'], unique=False)
    op.create_index(op.f('ix_pawapay_deposits_order_id'), 'pawapay_deposits', ['order_id'], unique=False)
    op.create_table('pawapay_payouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payout_id', sa.String(length=64), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('business_id', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=32), nullable=True),
    sa.Column('provider', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.String(length=256), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payout_id', name='uq_pawapay_payout_id')
    )
    op.create_index(op.f('ix_pawapay_payouts_business_id'), 'pawapay_payouts', ['business_id'], unique=False)
    op.create_index(op.f('ix_pawapay_payouts_order_id'), 'pawapay_payouts', ['order_id'], unique=False)
    op.create_index(op.f('ix_pawapay_payouts_payout_id'), 'pawapay_payouts', ['payout_id'], unique=False)
    op.create_table('pawapay_refunds',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('refund_id', sa.String(length=64), nullable=False),
    sa.Column('deposit_id', sa.String(length=64), nullable=True),
    sa.Column('order_id', sa.String(length=64), nullable=True),
    sa.Column('business_id', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('failure_code', sa.String(length=64), nullable=True),
    sa.Column('failure_message', sa.String(length=256), nullable=True),
    sa.Column('meta', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refund_id', name='uq_pawapay_refund_id')
    )
    op.create_index(op.f('ix_pawapay_refunds_business_id'), 'pawapay_refunds', ['business_id'], unique=False)
    op.create_index(op.f('ix_pawapay_refunds_deposit_id'), 'pawapay_refunds', ['deposit_id'], unique=False)
    op.create_index(op.f('ix_pawapay_refunds_order_id'), 'pawapay_refunds', ['order_id'], unique=False)
    op.create_index(op.f('ix_pawapay_refunds_refund_id'), 'pawapay_refunds', ['refund_id'], unique=False)
    op.create_table('payouts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('payee_type', sa.String(length=32), nullable=False),
    sa.Column('payee_id', sa.String(length=64), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'payee_type', name='uq_payout_order_payee_type')
    )
    op.create_index(op.f('ix_payouts_business_id'), 'payouts', ['business_id'], unique=False)
    op.create_index(op.f('ix_payouts_order_id'), 'payouts', ['order_id'], unique=False)
    op.create_index(op.f('ix_payouts_payee_id'), 'payouts', ['payee_id'], unique=False)
    op.create_index(op.f('ix_payouts_payee_type'), 'payouts', ['payee_type'], unique=False)
    op.create_index(op.f('ix_payouts_payment_id'), 'payouts', ['payment_id'], unique=False)
    op.create_table('settlements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=64), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('fee_bps', sa.Integer(), nullable=False),
    sa.Column('platform_fee_minor', sa.Integer(), nullable=False),
    sa.Column('affiliate_commission_minor', sa.Integer(), nullable=False),
    sa.Column('msme_net_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', name='uq_settlement_order'),
    sa.UniqueConstraint('payment_id', name='uq_settlement_payment')
    )
    op.create_index(op.f('ix_settlements_business_id'), 'settlements', ['business_id'], unique=False)
    op.create_index(op.f('ix_settlements_order_id'), 'settlements', ['order_id'], unique=False)
    op.create_index(op.f('ix_settlements_payment_id'), 'settlements', ['payment_id'], unique=False)
    op.create_table('subscription_payments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('payment_id', sa.String(length=64), nullable=False),
    sa.Column('business_id', sa.String(length=64), nullable=False),
    sa.Column('plan', sa.String(length=32), nullable=False),
    sa.Column('paid_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('dispatched', sa.Boolean(), nullable=False),
    sa.Column('meta', sqlite.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payment_id', name='uq_sub_payment_payment')
    )
    op.create_index(op.f('ix_subscription_payments_business_id'), 'subscription_payments', ['business_id'], unique=False)
    op.create_index(op.f('ix_subscription_payments_payment_id'), 'subscription_payments', ['payment_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subscription_payments_payment_id'), table_name='subscription_payments')
    op.drop_index(op.f('ix_subscription_payments_business_id'), table_name='subscription_payments')
    op.drop_table('subscription_payments')
    op.drop_index(op.f('ix_settlements_payment_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_order_id'), table_name='settlements')
    op.drop_index(op.f('ix_settlements_business_id'), table_name='settlements')
    op.drop_table('settlements')
    op.drop_index(op.f('ix_payouts_payment_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_payee_type'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_payee_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_order_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_business_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_pawapay_refunds_refund_id'), table_name='pawapay_refunds')
    op.drop_index(op.f('ix_pawapay_refunds_order_id'), table_name='pawapay_refunds')
    op.drop_index(op.f('ix_pawapay_refunds_deposit_id'), table_name='pawapay_refunds')
    op.drop_index(op.f('ix_pawapay_refunds_business_id'), table_name='pawapay_refunds')
    op.drop_table('pawapay_refunds')
    op.drop_index(op.f('ix_pawapay_payouts_payout_id'), table_name='pawapay_payouts')
    op.drop_index(op.f('ix_pawapay_payouts_order_id'), table_name='pawapay_payouts')
    op.drop_index(op.f('ix_pawapay_payouts_business_id'), table_name='pawapay_payouts')
    op.drop_table('pawapay_payouts')
    op.drop_index(op.f('ix_pawapay_deposits_order_id'), table_name='pawapay_deposits')
    op.drop_index(op.f('ix_pawapay_deposits_deposit_id'), table_name='pawapay_deposits')
    op.drop_index(op.f('ix_pawapay_deposits_business_id'), table_name='pawapay_deposits')
    op.drop_table('pawapay_deposits')
    op.drop_index(op.f('ix_outbox_topic'), table_name='outbox')
    op.drop_table('outbox')
    op.drop_index(op.f('ix_idempotency_records_scope'), table_name='idempotency_records')
    op.drop_index(op.f('ix_idempotency_records_key'), table_name='idempotency_records')
    op.drop_table('idempotency_records')
    # ### end Alembic commands ###
