"""Add affiliate_payout_records table

Revision ID: d1
Revises: c4292361a706
Create Date: 2026-01-28 15:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1'
down_revision = 'c4292361a706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliate_payout_records',
    sa.Column('id', sa.String(36), nullable=False),
    sa.Column('payout_id', sa.String(36), nullable=False),
    sa.Column('batch_id', sa.String(36), nullable=False),
    sa.Column('epoch_id', sa.String(36), nullable=False),
    sa.Column('affiliate_id', sa.String(36), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(8), nullable=False),
    sa.Column('status', sa.String(50), nullable=False),
    sa.Column('failure_message', sa.String(512), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('initiated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('payout_id', name='uq_affiliate_payout_id'),
    sa.UniqueConstraint('batch_id', 'affiliate_id', name='uq_affiliate_payout_batch_aff')
    )
    op.create_index(op.f('ix_affiliate_payout_records_affiliate_id'), 'affiliate_payout_records', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_payout_records_epoch_id'), 'affiliate_payout_records', ['epoch_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_affiliate_payout_records_epoch_id'), table_name='affiliate_payout_records')
    op.drop_index(op.f('ix_affiliate_payout_records_affiliate_id'), table_name='affiliate_payout_records')
    op.drop_table('affiliate_payout_records')
    # ### end Alembic commands ###
