"""Ports for durable, privacy-scoped customer memory."""

from __future__ import annotations

from datetime import datetime
from typing import Protocol

from ntheemba.domain.customer_memory import (
    ConversationMessage,
    ConversationSummary,
    CustomerAddress,
    CustomerConsent,
    CustomerPreference,
    CustomerQuestion,
    RetentionResult,
)


class CustomerMemoryRepository(Protocol):
    async def get_consent(self, customer_id: str, consent_type: str) -> CustomerConsent | None: ...
    async def save_consent(self, consent: CustomerConsent) -> CustomerConsent: ...
    async def list_addresses(self, customer_id: str, *, business_id: str | None) -> tuple[CustomerAddress, ...]: ...
    async def save_address(self, address: CustomerAddress) -> CustomerAddress: ...
    async def list_preferences(self, customer_id: str, *, business_id: str | None) -> tuple[CustomerPreference, ...]: ...
    async def save_preference(self, preference: CustomerPreference) -> CustomerPreference: ...
    async def record_message(self, message: ConversationMessage) -> None: ...
    async def record_summary(self, summary: ConversationSummary) -> None: ...
    async def record_question(self, question: CustomerQuestion) -> None: ...
    async def list_summaries(self, business_id: str, customer_id: str, *, limit: int = 50) -> tuple[ConversationSummary, ...]: ...
    async def list_questions(self, business_id: str, customer_id: str, *, limit: int = 50) -> tuple[CustomerQuestion, ...]: ...
    async def delete_customer(self, customer_id: str) -> None: ...
    async def cleanup(self, *, message_cutoff: datetime, summary_cutoff: datetime, question_cutoff: datetime, unsupported_cutoff: datetime) -> RetentionResult: ...
