"""Pure domain models and workflow rules for Ntheemba."""

from ntheemba.domain.booking_draft import (
    AppointmentSlot,
    BookingDraft,
    BookingStaffOption,
    ServiceSelection,
)
from ntheemba.domain.business import (
    BusinessChannel,
    BusinessProfile,
    ChannelBinding,
    ChannelRole,
    ChannelScope,
    PlatformCapability,
    ResolvedBusinessContext,
    ResolvedPlatformContext,
)
from ntheemba.domain.capabilities import (
    Capability,
    CapabilityCatalogue,
    CapabilityDeclarationResult,
    CapabilityDefinition,
)
from ntheemba.domain.conversation_plan import (
    ConversationPlan,
    PlannedWorkflow,
    PlannedWorkflowKind,
    PlannedWorkflowStatus,
)
from ntheemba.domain.customers import (
    BusinessClientLink,
    LoyaltyStatus,
    MinimalBusinessClient,
    PlatformCustomer,
    normalize_phone_e164,
)
from ntheemba.domain.enums import (
    ConversationMode,
    Flow,
    FulfilmentMethod,
    HandoverStatus,
    IntentType,
    ItemType,
    MessageRole,
    ProductResolutionStatus,
    RelativeSize,
    SessionStatus,
    Stage,
)
from ntheemba.domain.gateway import (
    InboundGatewayMessage,
    OutboundGatewayMessage,
)
from ntheemba.domain.intents import EntitySet, Intent, PendingQuestion
from ntheemba.domain.marketplace import (
    MarketplaceBusinessHandoffContext,
    MarketplaceBusinessListing,
    MarketplaceDiscoveryFilter,
    MarketplaceHandoff,
    MarketplaceHandoffStatus,
    MarketplaceListingStatus,
    MarketplaceProductOffer,
    MarketplaceProductSearch,
)
from ntheemba.domain.order_draft import OrderDraft, PriceSnapshot
from ntheemba.domain.product_resolution import (
    ProductCandidate,
    ProductQuery,
    ProductResolution,
    ResolvedProduct,
)
from ntheemba.domain.session import ConversationTurn, Session, SuspendedState
from ntheemba.domain.tradeflow_contract import (
    TradeFlowOperation,
    TradeFlowRequest,
    TradeFlowResponse,
    UnknownTradeFlowOperationError,
    capability_for_operation,
    parse_tradeflow_operation,
)
from ntheemba.domain.transitions import (
    InvalidTransitionError,
    TransitionContext,
    TransitionPolicy,
    TransitionTarget,
)

__all__ = [
    "AppointmentSlot",
    "BookingDraft",
    "BookingStaffOption",
    "BusinessChannel",
    "BusinessClientLink",
    "BusinessProfile",
    "ChannelBinding",
    "ChannelRole",
    "ChannelScope",
    "Capability",
    "CapabilityCatalogue",
    "CapabilityDeclarationResult",
    "CapabilityDefinition",
    "ConversationMode",
    "ConversationPlan",
    "ConversationTurn",
    "EntitySet",
    "Flow",
    "FulfilmentMethod",
    "HandoverStatus",
    "InboundGatewayMessage",
    "Intent",
    "IntentType",
    "InvalidTransitionError",
    "ItemType",
    "LoyaltyStatus",
    "MessageRole",
    "MarketplaceBusinessHandoffContext",
    "MarketplaceBusinessListing",
    "MarketplaceDiscoveryFilter",
    "MarketplaceHandoff",
    "MarketplaceHandoffStatus",
    "MarketplaceListingStatus",
    "MarketplaceProductOffer",
    "MarketplaceProductSearch",
    "MinimalBusinessClient",
    "OrderDraft",
    "OutboundGatewayMessage",
    "PendingQuestion",
    "PlannedWorkflow",
    "PlannedWorkflowKind",
    "PlannedWorkflowStatus",
    "PlatformCustomer",
    "PlatformCapability",
    "PriceSnapshot",
    "ProductCandidate",
    "ProductQuery",
    "ProductResolution",
    "ProductResolutionStatus",
    "RelativeSize",
    "ResolvedBusinessContext",
    "ResolvedPlatformContext",
    "ResolvedProduct",
    "ServiceSelection",
    "Session",
    "SessionStatus",
    "Stage",
    "SuspendedState",
    "TradeFlowOperation",
    "TradeFlowRequest",
    "TradeFlowResponse",
    "TransitionContext",
    "TransitionPolicy",
    "TransitionTarget",
    "UnknownTradeFlowOperationError",
    "capability_for_operation",
    "normalize_phone_e164",
    "parse_tradeflow_operation",
]
