import os
import sys
import asyncio


def _add_app_path():
    here = os.path.dirname(__file__)
    app_dir = os.path.normpath(os.path.join(here, "..", "app"))
    if app_dir not in sys.path:
        sys.path.insert(0, app_dir)


_add_app_path()

import runtime_engine as engine  # type: ignore


class DummyStore:
    async def create_default_if_missing(self, session_id):
        return ({"meta": {}}, 1)

    async def cas_update(self, session_id, updater):
        oob = {"meta": {}}
        updated = updater(oob)
        return (updated, 1)

    async def set_last_event(self, session_id, event_id):
        return True


class DummyIce:
    def __init__(self):
        self.enabled = False


def test_missing_slots_nlg_integration():
    # patch runtime dependencies to avoid external Redis/ICE, but use real Gemini
    engine.OOBStore = DummyStore
    engine.IceClient = DummyIce

    payload = {"meta": {"session": {"stage": "cart"}}, "text": "I want to buy"}

    res = asyncio.run(engine.process_event(payload=payload, event_id="evt-integ", session_id="sess-integ"))

    assert isinstance(res, dict)
    assert res.get("render_type") == "nlg"
    tpl_vars = res.get("template_vars") or {}
    assert "missing_slots" in tpl_vars
    # reply_text should be generated by Gemini and non-empty
    assert isinstance(res.get("reply_text"), str) and res.get("reply_text").strip()
import os
import sys
import asyncio


def _add_app_path():
    here = os.path.dirname(__file__)
    app_dir = os.path.normpath(os.path.join(here, "..", "app"))
    if app_dir not in sys.path:
        sys.path.insert(0, app_dir)


_add_app_path()

import runtime_engine as engine  # type: ignore


class DummyStore:
    async def create_default_if_missing(self, session_id):
        return ({"meta": {}}, 1)

    async def cas_update(self, session_id, updater):
        oob = {"meta": {}}
        return (updater(oob), 1)

    async def set_last_event(self, session_id, event_id):
        return True


class DummyIce:
    def __init__(self):
        self.enabled = False


def _load_env_file(path: str):
    # load .env key=val lines into environment (no output)
    try:
        with open(path, "r", encoding="utf-8") as f:
            for ln in f:
                ln = ln.strip()
                if not ln or ln.startswith("#"):
                    continue
                if "=" not in ln:
                    continue
                k, v = ln.split("=", 1)
                os.environ.setdefault(k.strip(), v.strip())
    except Exception:
        pass


def test_missing_slots_nlg_integration():
    # ensure env from repo .env is loaded so renderer can find keys
    _load_env_file(os.path.join(os.path.dirname(__file__), "..", "..", ".env"))

    # Map INTENT_* vars to GEMINI_* expected by renderer
    if os.environ.get("INTENT_GEMINI_API_KEY") and not os.environ.get("GEMINI_API_KEY"):
        os.environ["GEMINI_API_KEY"] = os.environ.get("INTENT_GEMINI_API_KEY")
    if os.environ.get("INTENT_GEMINI_MODEL") and not os.environ.get("GEMINI_MODEL"):
        os.environ["GEMINI_MODEL"] = os.environ.get("INTENT_GEMINI_MODEL")

    engine.OOBStore = DummyStore
    engine.IceClient = DummyIce

    payload = {"meta": {"session": {"stage": "cart"}}, "text": "I want to buy"}

    # run runtime which should call through to nlg_renderer.render_reply
    res = asyncio.run(engine.process_event(payload=payload, event_id="evt-int", session_id="sess-int"))

    assert isinstance(res, dict)
    assert res.get("render_type") == "nlg"
    reply = res.get("reply_text")
    assert isinstance(reply, str) and reply.strip(), "Expected non-empty reply_text from Gemini"
